---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```
<br>

####Welcome  
  
Welcome to this little corner of the web I have claimed for myself. Short disclaimer: this site is still very much under construction. At the moment, it's main purpose is for it to have my updated publication list. I also use it as a platform for me to disseminate some of the "failed" studies that I have ran in an effort to be fully transparent about the research I am conducting.

I am a big believer in transparency and believe that sharing data and statistical code is an absolute necessity. The data and code for my studies is available on open science and the current site contains links to each. 

Thank you for your interest, <br>
Never hesitate to send me an email, <br>
-Dries H. Bostyn-
<br>
<br>

####Currently Working on:  
-  a manuscript exploring the judgment-behavior gap in moral cognition (Under Review)  
-  a manuscript exploring the the generalizability of consequentialist moral judgment across moral domains (Under Review)  
-  a manuscript exploring individual differences in implicit moral rule usage (In Prep)
-  a number of different series of studies related to scientific 'awe' (Gathering Data)

<br>
