---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>
This page contains a list of some of my research projects that never really went anywhere.

I believe it is important to at least make a minimal effort to share the research work I've done that never really panned out. Mostly because I feel it is important in the face of the publication bias against null results.

For all projects included in this list, at least one study was ran and data was collected. These studies are not discussed in full because either:

- only small amounts of data were gathered
- the data was gathered in a messy way and I haven't yet found the time or willpower to clean it up to make it easily digestible
- results were simply not interesting enough to warrant further discussion

Some of these projects were motivated by a clear theoretical reason. Some others studies were ran because I simply liked the idea. In any case, if any of these projects sound interesting to you, or you would like to receive the data, don't hesitate to send me an e-mail. I do not mind disseminating the results of these projects to interested parties. 

***

####The list of studies that never really panned out
- A Cognitive Load study using both personal/impersonal dilemmas and the "white lie" dilemmas from <a href="https://dx.doi.org/10.1093/scan/nsr005">Kahane et al.</a> Results were messy, and made little theoretical sense.
 
- A study investigating if Intentional Binding is associated with increased deontological thinking. First study uncovered a significant positive association. The replication study failed to corroborate this effect. Project was abandoned because the data for both studies was very messy.

- A study on political ideology and <a href="https://www.gapminder.org/ignorance/">Global Ignorance</a>. Null effects in a sufficiently large sample.

- A study on politcal ideology and the monetary valuation of human life. Smallish sample but results did not suggest any particular association.

- A number of studies on atheist beliefs and their relation to dogmatism and need for closure. Three studies were conducted. Hopeful, but not great results that by and large were similar to results by <a href="https://dx.doi.org/10.1111/bjop.12186">Kossowska et al.</a>

- A study investigating racism and preference for consequentialist moral judgment. Small pilot study uncovered a large positive association. Large mTurk replication failed to replicate the effect.
A study investigating if completing trolley dilemmas influenced participants' perception of their own moral values. Some minor but fairly uninteresting effects were uncovered.

- A study investigating if video game behavior is associated with consequentialist moral preference. Messy data that hinted at a small effect.

- A study investigating gender stereotypes and their influence on trust in utilitarians / deontologists. By and large no effects of Gender stereotypes. The basic finding of increased trust in deontologists did replicate.


<br>
